[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --ignore-platform-reqs --optimize-autoloader --no-dev --no-interaction --prefer-dist",
    "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "php artisan optimize && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
